version: '2'
services:
  scarf-similarity-mysql:
    image: mysql:5.5
    container_name: scarf-similarity-mysql
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_bin
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=user 
      - MYSQL_PASSWORD=password 
      - MYSQL_DATABASE=KnowledgeBase 
      - MYSQL_ROOT_PASSWORD=password2
    volumes:
      - "./knowledge_db/localdb-run.sh:/localdb-run.sh"
      - "./knowledge_db/data/CaseBase.sql:/docker-entrypoint-initdb.d/CaseBase.sql"
      - "./data-similarity-engine-database:/var/lib/mysql:rw"
    networks:
      - mysql_net
  scarf-similarity-engine:
    build: ./similarity_engine/
    links:
      - scarf-similarity-mysql:scarf-similarity-mysql
    depends_on:
      - scarf-similarity-mysql
    ports:
      - "8095:8080"
    networks:
      - mysql_net
networks:
  mysql_net: