version: '2'
services:
  mysql:
    build: ./knowledge_db/
    container_name: knowledge-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=user 
      - MYSQL_PASSWORD=password 
      - MYSQL_DATABASE=KnowledgeBase 
      - MYSQL_ROOT_HOST=172.17.0.1 
    networks:
      - mysql_net
  similarity-engine:
    build: ./similarity_engine/
    links:
      - mysql:mysql
    depends_on:
      - mysql
    ports:
      - "8095:8080"
    networks:
      - mysql_net
networks:
  mysql_net:
    driver: bridge